[tool.poetry]
name = "afm-vlm"
version = "0.1.0"
description = ""
authors = ["azza <azza.baatout@adesso.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
